submissionAPI:
  host: localhost
  port: 80
  certPath: cert.pem
  keyPath: key.pem

whois:
  host: v4.whois.cymru.com
  port: 43
  timeout: 5s
  keepAlive: 10s

statsd:
  host: localhost
  port: 8125

dbURI: something

submissionWorkers: 5

nssPoolPEM: roots/nss_list.pem
msPoolPEM: roots/ms_list.pem
transPoolPEM: roots/trans_list.pem
